### PR TITLE
test: 1.3.1 test build

### PR DESCRIPTION
**Pull request by Exulansis**

### CODE REVIEW

**Comment by paultonga** [comment]
Building the android Smart Wallet using the `tar.gz` file provided in this branch produces this error:
```
/Users/paultonga/Projects/Jolocom/smart-wallet-mirror-private/node_modules/@jolocom/native-core-react-native/android/src/main/java/io/jolocom/jolocomCore/JolocomCoreModule.java:344: error: ',', ')', or '[' expected
                      String key_id, String sign_key_id, String message String header);
                                                                       ^
1 error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':jolocom_native-core-react-native:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

```

Also, while trying to pack the library, I get this error, which looks like the one above:
```
rror[E0061]: this function takes 4 arguments but 6 arguments were supplied
   --> src/lib.rs:115:9
    |
115 |         wallet::seal_didcomm_message(&ew, &id, &pass, &key_id, &message, &header)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ---  ---  -----  -------  --------  ------- supplied 6 arguments
    |         |
    |         expected 4 arguments
    |
note: function defined here
   --> /Users/paultonga/Projects/Jolocom/rust-multi-target/rust/jolocom_native_utils/src/wallet/didcomm.rs:21:8
    |
21  | pub fn seal_didcomm_message(
    |        ^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> src/lib.rs:115:9
    |
114 |         -> Result<String, String> {
    |            ---------------------- expected `Result<std::string::String, std::string::String>` because of return type
115 |         wallet::seal_didcomm_message(&ew, &id, &pass, &key_id, &message, &header)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `std::string::String`, found enum `jolocom_native_utils::error::Error`
    |
    = note: expected enum `Result<_, std::string::String>`
               found enum `Result<_, jolocom_native_utils::error::Error>`

error[E0061]: this function takes 4 arguments but 7 arguments were supplied
   --> src/lib.rs:120:9
    |
120 |         wallet::seal_didcomm_message(&ew, &id, &pass, &key_id, &sign_key_id, &message, &header)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ---  ---  -----  -------  ------------  --------  ------- supplied 7 arguments
    |         |
    |         expected 4 arguments
    |
note: function defined here
   --> /Users/paultonga/Projects/Jolocom/rust-multi-target/rust/jolocom_native_utils/src/wallet/didcomm.rs:21:8
    |
21  | pub fn seal_didcomm_message(
    |        ^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> src/lib.rs:120:9
    |
119 |         -> Result<String, String> {
    |            ---------------------- expected `Result<std::string::String, std::string::String>` because of return type
120 |         wallet::seal_didcomm_message(&ew, &id, &pass, &key_id, &sign_key_id, &message, &header)
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `std::string::String`, found enum `jolocom_native_utils::error::Error`
    |
    = note: expected enum `Result<_, std::string::String>`
               found enum `Result<_, jolocom_native_utils::error::Error>`

error[E0061]: this function takes 4 arguments but 6 arguments were supplied
   --> src/lib.rs:129:13
    |
129 |             wallet::receive_didcomm_message(&ew, &id, &pass, &message.as_bytes(), &sender_public_key.as_bytes(), vk)
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ---  ---  -----  -------------------  -----------------------------  -- supplied 6 arguments
    |             |
    |             expected 4 arguments
    |
note: function defined here
   --> /Users/paultonga/Projects/Jolocom/rust-multi-target/rust/jolocom_native_utils/src/wallet/didcomm.rs:41:8
    |
41  | pub fn receive_didcomm_message(
    |        ^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
   --> src/lib.rs:129:13
    |
124 |         -> Result<String, String> {
    |            ---------------------- expected `Result<std::string::String, std::string::String>` because of return type
...
129 |             wallet::receive_didcomm_message(&ew, &id, &pass, &message.as_bytes(), &sender_public_key.as_bytes(), vk)
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected struct `std::string::String`, found enum `jolocom_native_utils::error::Error`
    |
    = note: expected enum `Result<_, std::string::String>`
               found enum `Result<_, jolocom_native_utils::error::Error>`

```

**Comment by Exulansis** [comment]
Will take a look at this slightly later today, and report back by tomorrow morning. It looks like there's a coma missing [here](https://github.com/jolocom/rust-multi-target/commit/1353b4c6d3b5c1c2972b5e213272ae3bc12f121d#diff-a60ee8cd13e3899d608c97b44dbdbe13d71b1e5a45896a1951a1e55152309b3dR344). I guess adding the comma should help with the issue.

I have a suspicion this is what was fixed in the 1.3.0 release absent on Github but present on NPM, but I can only validate this later today.

**Comment by Exulansis** [comment]
Can you give it another try?

**Comment by Exulansis** [comment]
@thwalln I've rebuilt the tar.gz. All files except the `build.gradle` should be exactly identical to the ones on npm now (for 1.3.0).
Perhaps I've made some mistake last time I pushed.

Also It's quite important to clear the npm cache before trying out this version. I'm pretty sure NPM will try be clever, and (because the version 1.3.1 did not change across packages) might skip actually trying to install the new version. 

I guess `yarn cache clean` should suffice.

**Review by thwalln — DISMISSED** [review]

**Review by HedayatAbedijoo — APPROVED** [review]

**Review by thwalln — APPROVED** [review]

**Pull request merged**
